services:
  pertashop-app:
    build:
      args:
        user: pertashop
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pertashop
    container_name: pertashop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - msa-networks

  pertashop-nginx:
    image: nginx:alpine
    container_name: pertashop-nginx
    restart: unless-stopped
    ports:
      - 8101:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - msa-networks
  pertashop-mysql:
    image: mysql:latest
    container_name: pertashop-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3314:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "PertashopKurBro#1"
    networks:
      - msa-networks

networks:
  msa-networks:
    driver: bridge
    name: msa-networks
    external: true
